#!/usr/bin/env python3
"""
Convert the per-view landmark CSVs from hand_pose.py into the OpenPose-style
JSON that Pose2Sim triangulates, so the two views can be reconstructed in true
metric 3D once the cameras are calibrated.

Why this exists: Pose2Sim pairs the two cameras' JSON files *by index* -- the
Nth file of cam1 is assumed simultaneous with the Nth file of cam2. Our two
recordings are free-running phones at different fps, so this script resamples
the secondary view onto the primary view's frame timeline using the audio
offset from sync_audio.py (the same pairing fuse_views.py does). Index-paired
files therefore come out time-aligned.

Keypoint order is unchanged: Pose2Sim's HAND_21 skeleton (RWrist, RThumb1..4,
RIndex1..4, RMiddle1..4, RRing1..4, RPinky1..4) is landmark-for-landmark
identical to MediaPipe's 0..20, so ids pass through 1:1.

Output layout (what Pose2Sim expects):
    <out-dir>/
      Config.toml            generated stub, pose_model = 'HAND'
      calibration/           put your ChArUco/checkerboard calibration here
      pose/
        cam1_json/cam1_000000.json ...   primary view   (camera 1)
        cam2_json/cam2_000000.json ...   secondary view (camera 2)

Usage:
    python export_pose2sim.py --grasp Cilindrico
    python export_pose2sim.py --primary-csv out/Pinch/der.csv \
        --primary-video "Videos Cinves/Pinch_Derecha.mp4" \
        --secondary-csv out/Pinch/izq.csv \
        --secondary-video "Videos Cinves/Pinch_Izquierda.mp4" \
        --sync out/Pinch/sync.json --out-dir pose2sim/Pinch
"""
import argparse
import csv
import json
import os

import cv2

N_LANDMARKS = 21

# Default video names per grasp, mirroring batch_all.py.
V = "Videos Cinves"
PAIRS = {
    "Cilindrico":  (f"{V}/Cilíndrico_Derecha.mp4",   f"{V}/Cilíndrico_Izquierda.mp4"),
    "Esferico":    (f"{V}/Esférico_Derecha.mp4",     f"{V}/Esférico_Izquierda.mp4"),
    "Pinch":       (f"{V}/Pinch_Derecha.mp4",        f"{V}/Pinch_Izquierda.mp4"),
    "Disco":       (f"{V}/Disco_Derecha.mp4",        f"{V}/Disco_Izquierda.mp4"),
    "Plano":       (f"{V}/Plano_Derecha.mp4",        f"{V}/Plano_Izquierda.mp4"),
    "SelfieStick": (f"{V}/Selfie_Stick_Derecha.mp4", f"{V}/Selfie_Stick_Izquierda.mp4"),
}


def video_props(path):
    """(fps, width, height) of a video."""
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        raise SystemExit(f"Could not open {path}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    n = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return fps, w, h, n


def load(csv_path, w, h):
    """frame -> {hand_index: (score, label, {lid: (x_px, y_px)})}.

    Pixel coords are recomputed from the normalized columns rather than read
    from x_px/y_px, which hand_pose.py rounds to whole pixels -- triangulation
    is worth the sub-pixel precision.
    """
    out = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            fr, hi = int(r["frame"]), int(r["hand_index"])
            hand = out.setdefault(fr, {}).setdefault(
                hi, (float(r["score"]), r["handedness"], {}))
            hand[2][int(r["landmark_id"])] = (float(r["x_norm"]) * w,
                                              float(r["y_norm"]) * h)
    return out


def pick_hand(hands, rule):
    """Choose one hand from a frame's detections. Returns (score, label, pts) or None."""
    if not hands:
        return None
    if rule == "first":
        return hands[min(hands)]
    if rule in ("Left", "Right"):
        cand = [v for v in hands.values() if v[1] == rule]
        return max(cand, key=lambda v: v[0]) if cand else None
    return max(hands.values(), key=lambda v: v[0])          # "best"


def people_block(hand):
    """OpenPose `people` list for one selected hand (empty if none)."""
    if hand is None:
        return []
    score, _, pts = hand
    kp = []
    for lid in range(N_LANDMARKS):
        if lid in pts:
            kp += [round(pts[lid][0], 3), round(pts[lid][1], 3), round(score, 4)]
        else:
            kp += [0.0, 0.0, 0.0]     # conf 0 -> Pose2Sim drops this camera for this point
    return [{
        "person_id": [-1],
        "pose_keypoints_2d": kp,
        "face_keypoints_2d": [], "hand_left_keypoints_2d": [], "hand_right_keypoints_2d": [],
        "pose_3d": [], "face_keypoints_3d": [],
        "hand_left_keypoints_3d": [], "hand_right_keypoints_3d": [],
    }]


CONFIG_TEMPLATE = """\
# Generated by export_pose2sim.py -- Pose2Sim config for a two-view hand trial.
#
# The 2D keypoints in pose/ are already time-aligned (the secondary view was
# resampled onto the primary view's frames using the audio offset), so
# Pose2Sim's own [synchronization] step is not needed.
#
# Before running, put a calibration in calibration/ as Calib.toml. Pose2Sim's
# own 'calculate' path detects a CHECKERBOARD, not a ChArUco board -- compute
# the ChArUco calibration with Caliscope, Anipose, or OpenCV
# (cv2.aruco.calibrateCameraCharuco), then import it here with 'convert'.

[project]
multi_person = false
frame_rate = {fps}
frame_range = 'all'

[pose]
pose_model = 'HAND'      # -> HAND_21, matches MediaPipe's 21 landmarks 1:1

[calibration]
calibration_type = 'convert'
   [calibration.convert]
   convert_from = 'caliscope'   # 'caliscope', 'anipose', 'qualisys', ...

[triangulation]
reproj_error_threshold_triangulation = 15   # px
likelihood_threshold_triangulation = 0.3
interp_if_gap_smaller_than = 10
undistort_points = false

[filtering]
type = 'butterworth'
   [filtering.butterworth]
   order = 4
   cut_off_frequency = 6
"""


def main():
    ap = argparse.ArgumentParser(description="MediaPipe CSVs -> Pose2Sim OpenPose JSON")
    ap.add_argument("--grasp", help=f"shortcut for a known pair: {', '.join(PAIRS)}")
    ap.add_argument("--primary-csv"), ap.add_argument("--primary-video")
    ap.add_argument("--secondary-csv"), ap.add_argument("--secondary-video")
    ap.add_argument("--sync", help="sync.json from sync_audio.py")
    ap.add_argument("--out-dir")
    ap.add_argument("--hand", default="best", choices=["best", "first", "Left", "Right"],
                    help="which detection to keep per frame (default: highest score). "
                         "Note the handedness LABEL flips between opposite camera "
                         "positions for the same physical hand, so filtering by it "
                         "silently drops frames.")
    args = ap.parse_args()

    if args.grasp:
        der_v, izq_v = PAIRS[args.grasp]
        args.primary_csv = args.primary_csv or f"out/{args.grasp}/der.csv"
        args.secondary_csv = args.secondary_csv or f"out/{args.grasp}/izq.csv"
        args.primary_video = args.primary_video or der_v
        args.secondary_video = args.secondary_video or izq_v
        args.sync = args.sync or f"out/{args.grasp}/sync.json"
        args.out_dir = args.out_dir or f"pose2sim/{args.grasp}"
    missing = [k for k in ("primary_csv", "primary_video", "secondary_csv",
                           "secondary_video", "sync", "out_dir") if not getattr(args, k)]
    if missing:
        raise SystemExit("missing arguments: " + ", ".join("--" + m.replace("_", "-")
                                                           for m in missing))

    fps_p, w_p, h_p, n_p = video_props(args.primary_video)
    fps_s, w_s, h_s, _ = video_props(args.secondary_video)
    offset = json.load(open(args.sync))["offset_sec"]   # sec_time = prim_time + offset

    prim = load(args.primary_csv, w_p, h_p)
    sec = load(args.secondary_csv, w_s, h_s)

    d1 = os.path.join(args.out_dir, "pose", "cam1_json")
    d2 = os.path.join(args.out_dir, "pose", "cam2_json")
    for d in (d1, d2, os.path.join(args.out_dir, "calibration")):
        os.makedirs(d, exist_ok=True)

    n_frames = n_p or (max(prim) + 1)
    hit1 = hit2 = both = 0
    for i in range(n_frames):
        h1 = pick_hand(prim.get(i, {}), args.hand)
        fs = round((i / fps_p + offset) * fps_s)          # matching secondary frame
        h2 = pick_hand(sec.get(fs, {}), args.hand)
        hit1 += h1 is not None
        hit2 += h2 is not None
        both += (h1 is not None) and (h2 is not None)
        for d, cam, hand in ((d1, "cam1", h1), (d2, "cam2", h2)):
            with open(os.path.join(d, f"{cam}_{i:06d}.json"), "w") as f:
                json.dump({"version": 1.3, "people": people_block(hand)}, f)

    cfg = os.path.join(args.out_dir, "Config.toml")
    with open(cfg, "w") as f:
        f.write(CONFIG_TEMPLATE.format(fps=round(fps_p, 3)))

    print(f"primary   {args.primary_video}  {w_p}x{h_p} @ {fps_p:.2f} fps")
    print(f"secondary {args.secondary_video}  {w_s}x{h_s} @ {fps_s:.2f} fps")
    print(f"audio offset               : {offset:+.4f} s")
    print(f"frames written per camera  : {n_frames}")
    print(f"  with a hand in cam1      : {hit1}")
    print(f"  with a hand in cam2      : {hit2}")
    print(f"  triangulable (both views): {both}  ({100*both/max(n_frames,1):.1f}%)")
    print(f"\n  -> {d1}")
    print(f"  -> {d2}")
    print(f"  -> {cfg}")
    print(f"\nNext: put your calibration in {args.out_dir}/calibration/Calib.toml, then")
    print("  from Pose2Sim import Pose2Sim; Pose2Sim.triangulation()")


if __name__ == "__main__":
    main()
